/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as PresencesRouteImport } from './routes/presences'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OuvriersIndexRouteImport } from './routes/ouvriers.index'
import { Route as SuiviReclamationsRouteImport } from './routes/suivi.reclamations'
import { Route as RecrutementEntretiensRouteImport } from './routes/recrutement.entretiens'
import { Route as RecrutementCandidaturesRouteImport } from './routes/recrutement.candidatures'
import { Route as RecrutementCampagnesRouteImport } from './routes/recrutement.campagnes'
import { Route as PilotageAlertesRouteImport } from './routes/pilotage.alertes'
import { Route as OuvriersIdRouteImport } from './routes/ouvriers.$id'
import { Route as FormationSessionsRouteImport } from './routes/formation.sessions'
import { Route as FormationQualiteRouteImport } from './routes/formation.qualite'
import { Route as FormationQcmRouteImport } from './routes/formation.qcm'
import { Route as FormationPlanningRouteImport } from './routes/formation.planning'
import { Route as FormationParcoursRouteImport } from './routes/formation.parcours'
import { Route as FormationQcmIndexRouteImport } from './routes/formation.qcm.index'
import { Route as RecrutementCandidatIdRouteImport } from './routes/recrutement.candidat.$id'
import { Route as FormationQcmNouvelleRouteImport } from './routes/formation.qcm.nouvelle'
import { Route as FormationQcmIdRouteImport } from './routes/formation.qcm.$id'

const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencesRoute = PresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvriersIndexRoute = OuvriersIndexRouteImport.update({
  id: '/ouvriers/',
  path: '/ouvriers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviReclamationsRoute = SuiviReclamationsRouteImport.update({
  id: '/suivi/reclamations',
  path: '/suivi/reclamations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementEntretiensRoute = RecrutementEntretiensRouteImport.update({
  id: '/recrutement/entretiens',
  path: '/recrutement/entretiens',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementCandidaturesRoute = RecrutementCandidaturesRouteImport.update({
  id: '/recrutement/candidatures',
  path: '/recrutement/candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementCampagnesRoute = RecrutementCampagnesRouteImport.update({
  id: '/recrutement/campagnes',
  path: '/recrutement/campagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotageAlertesRoute = PilotageAlertesRouteImport.update({
  id: '/pilotage/alertes',
  path: '/pilotage/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvriersIdRoute = OuvriersIdRouteImport.update({
  id: '/ouvriers/$id',
  path: '/ouvriers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationSessionsRoute = FormationSessionsRouteImport.update({
  id: '/formation/sessions',
  path: '/formation/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationQualiteRoute = FormationQualiteRouteImport.update({
  id: '/formation/qualite',
  path: '/formation/qualite',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationQcmRoute = FormationQcmRouteImport.update({
  id: '/formation/qcm',
  path: '/formation/qcm',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationPlanningRoute = FormationPlanningRouteImport.update({
  id: '/formation/planning',
  path: '/formation/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationParcoursRoute = FormationParcoursRouteImport.update({
  id: '/formation/parcours',
  path: '/formation/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationQcmIndexRoute = FormationQcmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormationQcmRoute,
} as any)
const RecrutementCandidatIdRoute = RecrutementCandidatIdRouteImport.update({
  id: '/recrutement/candidat/$id',
  path: '/recrutement/candidat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationQcmNouvelleRoute = FormationQcmNouvelleRouteImport.update({
  id: '/nouvelle',
  path: '/nouvelle',
  getParentRoute: () => FormationQcmRoute,
} as any)
const FormationQcmIdRoute = FormationQcmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FormationQcmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/communication': typeof CommunicationRoute
  '/presences': typeof PresencesRoute
  '/reporting': typeof ReportingRoute
  '/formation/parcours': typeof FormationParcoursRoute
  '/formation/planning': typeof FormationPlanningRoute
  '/formation/qcm': typeof FormationQcmRouteWithChildren
  '/formation/qualite': typeof FormationQualiteRoute
  '/formation/sessions': typeof FormationSessionsRoute
  '/ouvriers/$id': typeof OuvriersIdRoute
  '/pilotage/alertes': typeof PilotageAlertesRoute
  '/recrutement/campagnes': typeof RecrutementCampagnesRoute
  '/recrutement/candidatures': typeof RecrutementCandidaturesRoute
  '/recrutement/entretiens': typeof RecrutementEntretiensRoute
  '/suivi/reclamations': typeof SuiviReclamationsRoute
  '/ouvriers/': typeof OuvriersIndexRoute
  '/formation/qcm/$id': typeof FormationQcmIdRoute
  '/formation/qcm/nouvelle': typeof FormationQcmNouvelleRoute
  '/recrutement/candidat/$id': typeof RecrutementCandidatIdRoute
  '/formation/qcm/': typeof FormationQcmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/communication': typeof CommunicationRoute
  '/presences': typeof PresencesRoute
  '/reporting': typeof ReportingRoute
  '/formation/parcours': typeof FormationParcoursRoute
  '/formation/planning': typeof FormationPlanningRoute
  '/formation/qualite': typeof FormationQualiteRoute
  '/formation/sessions': typeof FormationSessionsRoute
  '/ouvriers/$id': typeof OuvriersIdRoute
  '/pilotage/alertes': typeof PilotageAlertesRoute
  '/recrutement/campagnes': typeof RecrutementCampagnesRoute
  '/recrutement/candidatures': typeof RecrutementCandidaturesRoute
  '/recrutement/entretiens': typeof RecrutementEntretiensRoute
  '/suivi/reclamations': typeof SuiviReclamationsRoute
  '/ouvriers': typeof OuvriersIndexRoute
  '/formation/qcm/$id': typeof FormationQcmIdRoute
  '/formation/qcm/nouvelle': typeof FormationQcmNouvelleRoute
  '/recrutement/candidat/$id': typeof RecrutementCandidatIdRoute
  '/formation/qcm': typeof FormationQcmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/communication': typeof CommunicationRoute
  '/presences': typeof PresencesRoute
  '/reporting': typeof ReportingRoute
  '/formation/parcours': typeof FormationParcoursRoute
  '/formation/planning': typeof FormationPlanningRoute
  '/formation/qcm': typeof FormationQcmRouteWithChildren
  '/formation/qualite': typeof FormationQualiteRoute
  '/formation/sessions': typeof FormationSessionsRoute
  '/ouvriers/$id': typeof OuvriersIdRoute
  '/pilotage/alertes': typeof PilotageAlertesRoute
  '/recrutement/campagnes': typeof RecrutementCampagnesRoute
  '/recrutement/candidatures': typeof RecrutementCandidaturesRoute
  '/recrutement/entretiens': typeof RecrutementEntretiensRoute
  '/suivi/reclamations': typeof SuiviReclamationsRoute
  '/ouvriers/': typeof OuvriersIndexRoute
  '/formation/qcm/$id': typeof FormationQcmIdRoute
  '/formation/qcm/nouvelle': typeof FormationQcmNouvelleRoute
  '/recrutement/candidat/$id': typeof RecrutementCandidatIdRoute
  '/formation/qcm/': typeof FormationQcmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/communication'
    | '/presences'
    | '/reporting'
    | '/formation/parcours'
    | '/formation/planning'
    | '/formation/qcm'
    | '/formation/qualite'
    | '/formation/sessions'
    | '/ouvriers/$id'
    | '/pilotage/alertes'
    | '/recrutement/campagnes'
    | '/recrutement/candidatures'
    | '/recrutement/entretiens'
    | '/suivi/reclamations'
    | '/ouvriers/'
    | '/formation/qcm/$id'
    | '/formation/qcm/nouvelle'
    | '/recrutement/candidat/$id'
    | '/formation/qcm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/communication'
    | '/presences'
    | '/reporting'
    | '/formation/parcours'
    | '/formation/planning'
    | '/formation/qualite'
    | '/formation/sessions'
    | '/ouvriers/$id'
    | '/pilotage/alertes'
    | '/recrutement/campagnes'
    | '/recrutement/candidatures'
    | '/recrutement/entretiens'
    | '/suivi/reclamations'
    | '/ouvriers'
    | '/formation/qcm/$id'
    | '/formation/qcm/nouvelle'
    | '/recrutement/candidat/$id'
    | '/formation/qcm'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/communication'
    | '/presences'
    | '/reporting'
    | '/formation/parcours'
    | '/formation/planning'
    | '/formation/qcm'
    | '/formation/qualite'
    | '/formation/sessions'
    | '/ouvriers/$id'
    | '/pilotage/alertes'
    | '/recrutement/campagnes'
    | '/recrutement/candidatures'
    | '/recrutement/entretiens'
    | '/suivi/reclamations'
    | '/ouvriers/'
    | '/formation/qcm/$id'
    | '/formation/qcm/nouvelle'
    | '/recrutement/candidat/$id'
    | '/formation/qcm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  CommunicationRoute: typeof CommunicationRoute
  PresencesRoute: typeof PresencesRoute
  ReportingRoute: typeof ReportingRoute
  FormationParcoursRoute: typeof FormationParcoursRoute
  FormationPlanningRoute: typeof FormationPlanningRoute
  FormationQcmRoute: typeof FormationQcmRouteWithChildren
  FormationQualiteRoute: typeof FormationQualiteRoute
  FormationSessionsRoute: typeof FormationSessionsRoute
  OuvriersIdRoute: typeof OuvriersIdRoute
  PilotageAlertesRoute: typeof PilotageAlertesRoute
  RecrutementCampagnesRoute: typeof RecrutementCampagnesRoute
  RecrutementCandidaturesRoute: typeof RecrutementCandidaturesRoute
  RecrutementEntretiensRoute: typeof RecrutementEntretiensRoute
  SuiviReclamationsRoute: typeof SuiviReclamationsRoute
  OuvriersIndexRoute: typeof OuvriersIndexRoute
  RecrutementCandidatIdRoute: typeof RecrutementCandidatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presences': {
      id: '/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof PresencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvriers/': {
      id: '/ouvriers/'
      path: '/ouvriers'
      fullPath: '/ouvriers/'
      preLoaderRoute: typeof OuvriersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/reclamations': {
      id: '/suivi/reclamations'
      path: '/suivi/reclamations'
      fullPath: '/suivi/reclamations'
      preLoaderRoute: typeof SuiviReclamationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement/entretiens': {
      id: '/recrutement/entretiens'
      path: '/recrutement/entretiens'
      fullPath: '/recrutement/entretiens'
      preLoaderRoute: typeof RecrutementEntretiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement/candidatures': {
      id: '/recrutement/candidatures'
      path: '/recrutement/candidatures'
      fullPath: '/recrutement/candidatures'
      preLoaderRoute: typeof RecrutementCandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement/campagnes': {
      id: '/recrutement/campagnes'
      path: '/recrutement/campagnes'
      fullPath: '/recrutement/campagnes'
      preLoaderRoute: typeof RecrutementCampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilotage/alertes': {
      id: '/pilotage/alertes'
      path: '/pilotage/alertes'
      fullPath: '/pilotage/alertes'
      preLoaderRoute: typeof PilotageAlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvriers/$id': {
      id: '/ouvriers/$id'
      path: '/ouvriers/$id'
      fullPath: '/ouvriers/$id'
      preLoaderRoute: typeof OuvriersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/sessions': {
      id: '/formation/sessions'
      path: '/formation/sessions'
      fullPath: '/formation/sessions'
      preLoaderRoute: typeof FormationSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/qualite': {
      id: '/formation/qualite'
      path: '/formation/qualite'
      fullPath: '/formation/qualite'
      preLoaderRoute: typeof FormationQualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/qcm': {
      id: '/formation/qcm'
      path: '/formation/qcm'
      fullPath: '/formation/qcm'
      preLoaderRoute: typeof FormationQcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/planning': {
      id: '/formation/planning'
      path: '/formation/planning'
      fullPath: '/formation/planning'
      preLoaderRoute: typeof FormationPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/parcours': {
      id: '/formation/parcours'
      path: '/formation/parcours'
      fullPath: '/formation/parcours'
      preLoaderRoute: typeof FormationParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/qcm/': {
      id: '/formation/qcm/'
      path: '/'
      fullPath: '/formation/qcm/'
      preLoaderRoute: typeof FormationQcmIndexRouteImport
      parentRoute: typeof FormationQcmRoute
    }
    '/recrutement/candidat/$id': {
      id: '/recrutement/candidat/$id'
      path: '/recrutement/candidat/$id'
      fullPath: '/recrutement/candidat/$id'
      preLoaderRoute: typeof RecrutementCandidatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/qcm/nouvelle': {
      id: '/formation/qcm/nouvelle'
      path: '/nouvelle'
      fullPath: '/formation/qcm/nouvelle'
      preLoaderRoute: typeof FormationQcmNouvelleRouteImport
      parentRoute: typeof FormationQcmRoute
    }
    '/formation/qcm/$id': {
      id: '/formation/qcm/$id'
      path: '/$id'
      fullPath: '/formation/qcm/$id'
      preLoaderRoute: typeof FormationQcmIdRouteImport
      parentRoute: typeof FormationQcmRoute
    }
  }
}

interface FormationQcmRouteChildren {
  FormationQcmIdRoute: typeof FormationQcmIdRoute
  FormationQcmNouvelleRoute: typeof FormationQcmNouvelleRoute
  FormationQcmIndexRoute: typeof FormationQcmIndexRoute
}

const FormationQcmRouteChildren: FormationQcmRouteChildren = {
  FormationQcmIdRoute: FormationQcmIdRoute,
  FormationQcmNouvelleRoute: FormationQcmNouvelleRoute,
  FormationQcmIndexRoute: FormationQcmIndexRoute,
}

const FormationQcmRouteWithChildren = FormationQcmRoute._addFileChildren(
  FormationQcmRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  CommunicationRoute: CommunicationRoute,
  PresencesRoute: PresencesRoute,
  ReportingRoute: ReportingRoute,
  FormationParcoursRoute: FormationParcoursRoute,
  FormationPlanningRoute: FormationPlanningRoute,
  FormationQcmRoute: FormationQcmRouteWithChildren,
  FormationQualiteRoute: FormationQualiteRoute,
  FormationSessionsRoute: FormationSessionsRoute,
  OuvriersIdRoute: OuvriersIdRoute,
  PilotageAlertesRoute: PilotageAlertesRoute,
  RecrutementCampagnesRoute: RecrutementCampagnesRoute,
  RecrutementCandidaturesRoute: RecrutementCandidaturesRoute,
  RecrutementEntretiensRoute: RecrutementEntretiensRoute,
  SuiviReclamationsRoute: SuiviReclamationsRoute,
  OuvriersIndexRoute: OuvriersIndexRoute,
  RecrutementCandidatIdRoute: RecrutementCandidatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
