/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresencesRouteImport } from './routes/presences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OuvriersIndexRouteImport } from './routes/ouvriers.index'
import { Route as SuiviObservationsRouteImport } from './routes/suivi.observations'
import { Route as RecrutementEntretiensRouteImport } from './routes/recrutement.entretiens'
import { Route as RecrutementCandidaturesRouteImport } from './routes/recrutement.candidatures'
import { Route as RecrutementCampagnesRouteImport } from './routes/recrutement.campagnes'
import { Route as PilotageAlertesRouteImport } from './routes/pilotage.alertes'
import { Route as OuvriersIdRouteImport } from './routes/ouvriers.$id'
import { Route as FormationSessionsRouteImport } from './routes/formation.sessions'
import { Route as FormationQcmRouteImport } from './routes/formation.qcm'
import { Route as FormationPlanningRouteImport } from './routes/formation.planning'
import { Route as FormationParcoursRouteImport } from './routes/formation.parcours'
import { Route as RecrutementCandidatIdRouteImport } from './routes/recrutement.candidat.$id'

const PresencesRoute = PresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvriersIndexRoute = OuvriersIndexRouteImport.update({
  id: '/ouvriers/',
  path: '/ouvriers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviObservationsRoute = SuiviObservationsRouteImport.update({
  id: '/suivi/observations',
  path: '/suivi/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementEntretiensRoute = RecrutementEntretiensRouteImport.update({
  id: '/recrutement/entretiens',
  path: '/recrutement/entretiens',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementCandidaturesRoute = RecrutementCandidaturesRouteImport.update({
  id: '/recrutement/candidatures',
  path: '/recrutement/candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementCampagnesRoute = RecrutementCampagnesRouteImport.update({
  id: '/recrutement/campagnes',
  path: '/recrutement/campagnes',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotageAlertesRoute = PilotageAlertesRouteImport.update({
  id: '/pilotage/alertes',
  path: '/pilotage/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvriersIdRoute = OuvriersIdRouteImport.update({
  id: '/ouvriers/$id',
  path: '/ouvriers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationSessionsRoute = FormationSessionsRouteImport.update({
  id: '/formation/sessions',
  path: '/formation/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationQcmRoute = FormationQcmRouteImport.update({
  id: '/formation/qcm',
  path: '/formation/qcm',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationPlanningRoute = FormationPlanningRouteImport.update({
  id: '/formation/planning',
  path: '/formation/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationParcoursRoute = FormationParcoursRouteImport.update({
  id: '/formation/parcours',
  path: '/formation/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementCandidatIdRoute = RecrutementCandidatIdRouteImport.update({
  id: '/recrutement/candidat/$id',
  path: '/recrutement/candidat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presences': typeof PresencesRoute
  '/formation/parcours': typeof FormationParcoursRoute
  '/formation/planning': typeof FormationPlanningRoute
  '/formation/qcm': typeof FormationQcmRoute
  '/formation/sessions': typeof FormationSessionsRoute
  '/ouvriers/$id': typeof OuvriersIdRoute
  '/pilotage/alertes': typeof PilotageAlertesRoute
  '/recrutement/campagnes': typeof RecrutementCampagnesRoute
  '/recrutement/candidatures': typeof RecrutementCandidaturesRoute
  '/recrutement/entretiens': typeof RecrutementEntretiensRoute
  '/suivi/observations': typeof SuiviObservationsRoute
  '/ouvriers/': typeof OuvriersIndexRoute
  '/recrutement/candidat/$id': typeof RecrutementCandidatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presences': typeof PresencesRoute
  '/formation/parcours': typeof FormationParcoursRoute
  '/formation/planning': typeof FormationPlanningRoute
  '/formation/qcm': typeof FormationQcmRoute
  '/formation/sessions': typeof FormationSessionsRoute
  '/ouvriers/$id': typeof OuvriersIdRoute
  '/pilotage/alertes': typeof PilotageAlertesRoute
  '/recrutement/campagnes': typeof RecrutementCampagnesRoute
  '/recrutement/candidatures': typeof RecrutementCandidaturesRoute
  '/recrutement/entretiens': typeof RecrutementEntretiensRoute
  '/suivi/observations': typeof SuiviObservationsRoute
  '/ouvriers': typeof OuvriersIndexRoute
  '/recrutement/candidat/$id': typeof RecrutementCandidatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presences': typeof PresencesRoute
  '/formation/parcours': typeof FormationParcoursRoute
  '/formation/planning': typeof FormationPlanningRoute
  '/formation/qcm': typeof FormationQcmRoute
  '/formation/sessions': typeof FormationSessionsRoute
  '/ouvriers/$id': typeof OuvriersIdRoute
  '/pilotage/alertes': typeof PilotageAlertesRoute
  '/recrutement/campagnes': typeof RecrutementCampagnesRoute
  '/recrutement/candidatures': typeof RecrutementCandidaturesRoute
  '/recrutement/entretiens': typeof RecrutementEntretiensRoute
  '/suivi/observations': typeof SuiviObservationsRoute
  '/ouvriers/': typeof OuvriersIndexRoute
  '/recrutement/candidat/$id': typeof RecrutementCandidatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/presences'
    | '/formation/parcours'
    | '/formation/planning'
    | '/formation/qcm'
    | '/formation/sessions'
    | '/ouvriers/$id'
    | '/pilotage/alertes'
    | '/recrutement/campagnes'
    | '/recrutement/candidatures'
    | '/recrutement/entretiens'
    | '/suivi/observations'
    | '/ouvriers/'
    | '/recrutement/candidat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/presences'
    | '/formation/parcours'
    | '/formation/planning'
    | '/formation/qcm'
    | '/formation/sessions'
    | '/ouvriers/$id'
    | '/pilotage/alertes'
    | '/recrutement/campagnes'
    | '/recrutement/candidatures'
    | '/recrutement/entretiens'
    | '/suivi/observations'
    | '/ouvriers'
    | '/recrutement/candidat/$id'
  id:
    | '__root__'
    | '/'
    | '/presences'
    | '/formation/parcours'
    | '/formation/planning'
    | '/formation/qcm'
    | '/formation/sessions'
    | '/ouvriers/$id'
    | '/pilotage/alertes'
    | '/recrutement/campagnes'
    | '/recrutement/candidatures'
    | '/recrutement/entretiens'
    | '/suivi/observations'
    | '/ouvriers/'
    | '/recrutement/candidat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresencesRoute: typeof PresencesRoute
  FormationParcoursRoute: typeof FormationParcoursRoute
  FormationPlanningRoute: typeof FormationPlanningRoute
  FormationQcmRoute: typeof FormationQcmRoute
  FormationSessionsRoute: typeof FormationSessionsRoute
  OuvriersIdRoute: typeof OuvriersIdRoute
  PilotageAlertesRoute: typeof PilotageAlertesRoute
  RecrutementCampagnesRoute: typeof RecrutementCampagnesRoute
  RecrutementCandidaturesRoute: typeof RecrutementCandidaturesRoute
  RecrutementEntretiensRoute: typeof RecrutementEntretiensRoute
  SuiviObservationsRoute: typeof SuiviObservationsRoute
  OuvriersIndexRoute: typeof OuvriersIndexRoute
  RecrutementCandidatIdRoute: typeof RecrutementCandidatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presences': {
      id: '/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof PresencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvriers/': {
      id: '/ouvriers/'
      path: '/ouvriers'
      fullPath: '/ouvriers/'
      preLoaderRoute: typeof OuvriersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/observations': {
      id: '/suivi/observations'
      path: '/suivi/observations'
      fullPath: '/suivi/observations'
      preLoaderRoute: typeof SuiviObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement/entretiens': {
      id: '/recrutement/entretiens'
      path: '/recrutement/entretiens'
      fullPath: '/recrutement/entretiens'
      preLoaderRoute: typeof RecrutementEntretiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement/candidatures': {
      id: '/recrutement/candidatures'
      path: '/recrutement/candidatures'
      fullPath: '/recrutement/candidatures'
      preLoaderRoute: typeof RecrutementCandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement/campagnes': {
      id: '/recrutement/campagnes'
      path: '/recrutement/campagnes'
      fullPath: '/recrutement/campagnes'
      preLoaderRoute: typeof RecrutementCampagnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilotage/alertes': {
      id: '/pilotage/alertes'
      path: '/pilotage/alertes'
      fullPath: '/pilotage/alertes'
      preLoaderRoute: typeof PilotageAlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvriers/$id': {
      id: '/ouvriers/$id'
      path: '/ouvriers/$id'
      fullPath: '/ouvriers/$id'
      preLoaderRoute: typeof OuvriersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/sessions': {
      id: '/formation/sessions'
      path: '/formation/sessions'
      fullPath: '/formation/sessions'
      preLoaderRoute: typeof FormationSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/qcm': {
      id: '/formation/qcm'
      path: '/formation/qcm'
      fullPath: '/formation/qcm'
      preLoaderRoute: typeof FormationQcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/planning': {
      id: '/formation/planning'
      path: '/formation/planning'
      fullPath: '/formation/planning'
      preLoaderRoute: typeof FormationPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/parcours': {
      id: '/formation/parcours'
      path: '/formation/parcours'
      fullPath: '/formation/parcours'
      preLoaderRoute: typeof FormationParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement/candidat/$id': {
      id: '/recrutement/candidat/$id'
      path: '/recrutement/candidat/$id'
      fullPath: '/recrutement/candidat/$id'
      preLoaderRoute: typeof RecrutementCandidatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresencesRoute: PresencesRoute,
  FormationParcoursRoute: FormationParcoursRoute,
  FormationPlanningRoute: FormationPlanningRoute,
  FormationQcmRoute: FormationQcmRoute,
  FormationSessionsRoute: FormationSessionsRoute,
  OuvriersIdRoute: OuvriersIdRoute,
  PilotageAlertesRoute: PilotageAlertesRoute,
  RecrutementCampagnesRoute: RecrutementCampagnesRoute,
  RecrutementCandidaturesRoute: RecrutementCandidaturesRoute,
  RecrutementEntretiensRoute: RecrutementEntretiensRoute,
  SuiviObservationsRoute: SuiviObservationsRoute,
  OuvriersIndexRoute: OuvriersIndexRoute,
  RecrutementCandidatIdRoute: RecrutementCandidatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
